// <auto-generated />
namespace AcunMedyaAkademiAgency.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig_4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_4));
        
        string IMigrationMetadata.Id
        {
            get { return "202502282007414_mig_4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
