// <auto-generated />
namespace AcunMedyaAkademiAgency.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig_yap : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_yap));
        
        string IMigrationMetadata.Id
        {
            get { return "202503010419348_mig_yap"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
